<a href="https://colab.research.google.com/github/vivekpugalenthi/calculator-app/blob/main/NumPy_paratics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import numpy as np
array=[1,2,3,4]
print(array)

[1, 2, 3, 4]


In [11]:
import numpy as np
array=np.array([1,2,3,4])
print(array)

[1 2 3 4]


In [12]:
import numpy as np
array=np.array([[1,2,3],[4,5,6]])
print(array)

[[1 2 3]
 [4 5 6]]


In [13]:
import numpy as np
array=np.array([1,2,3,4],ndmin=2)
print(array)

[[1 2 3 4]]


In [14]:
import  numpy as np
array=np.array([1,2,3],dtype=complex)
print(array)

[1.+0.j 2.+0.j 3.+0.j]


In [15]:
import numpy as np
array=np.array([[1,2,3],[4,5,6]])
print(array.shape)

(2, 3)


In [16]:
import numpy as np
array=np.array([[1,2,3],[4,5,6]])
array.shape=(3,2)
print(array)

[[1 2]
 [3 4]
 [5 6]]


In [17]:
import numpy as np
array=np.array([[1,2,3],[4,5,6]])
array2=np.array([[1,2,3],[4,5,6]])
print(np.hstack((array,array2)))

[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


In [18]:
import numpy as np
array=np.array([[1,2,3],[4,5,6]])
array2=np.array([[1,2,3],[4,5,6]])
print(np.vstack((array,array2)))

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]


In [19]:
import numpy as np
array=np.array([[1,2,3],[4,5,6]])
array2=np.array([[1,2,3],[4,5,6]])
print(np.column_stack((array,array2)))

[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


In [20]:
import numpy as np
array=np.array([[1,2,3],[4,5,6]])
array2=np.array([[1,2,3],[4,5,6]])
print(np.concatenate((array,array2),axis=0))

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]


In [21]:
import numpy as np
array=np.array([1,2,3,4,5,6])
print(np.array_split(array,3))

[array([1, 2]), array([3, 4]), array([5, 6])]


In [22]:
import numpy as np
array=np.array([[1,2,3],[4,5,6]])
print(np.array_split(array,3))

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([], shape=(0, 3), dtype=int64)]


In [23]:
import  numpy as np
array=np.array([1,2,3,4,5,6])
print(np.where(array==4))

(array([3]),)


In [24]:
import numpy as np
array=np.array([1,2,3,4,5,6])
print(np.sort(array))

[1 2 3 4 5 6]


In [25]:
import numpy as np
array=np.array([1,2,3,4,5,6])
x=[True,False,True,False,True,False]
newarray=array[x]
print(newarray)

[1 3 5]


In [33]:
import numpy as np
array=np.array([1,2,3,4,5,6])